- name: Setup Slurm Nodes
  hosts: all
  become: yes
  vars:
    slurm_version: "23.11.10"
    slurm_src_url: "https://download.schedmd.com/slurm/slurm-23.11.10.tar.bz2"
    slurm_build_dir: "/tmp/slurm-{{ slurm_version }}"
  tasks:

    - name: Install Chrony
      package:
        name:
          - chrony
        state: present
      become: yes

    - name: Configure Chrony to sync with controller-edge
      copy:
        src: /home/daisy/ansible-playbooks/chrony.conf
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: '0400'

    - name: Restart Chrony
      systemd:
        name: chronyd
        state: restarted
        enabled: yes

    - name: Install Munge
      package:
        name:
          - munge
        state: present
      become: yes

    - name: Copy Munge key from controller
      copy:
        src: /home/daisy/ansible-playbooks/munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'

    - name: Start and enable Munge
      systemd:
        name: munge
        state: restarted
        enabled: yes

    - name: Install Slurm Dependencies
      package:
        name:
          - build-essential
          - libssl-dev
          - libpam0g-dev
          - libmunge-dev
          - libreadline-dev
          - libncurses5-dev
          - libsqlite3-dev
          - libhdf5-dev
          - man-db
          - curl
          - python3
          - hwloc
          - libdbus-1-dev
        state: present
      become: yes

    - name: Download Slurm source code
      get_url:
        url: "{{ slurm_src_url }}"
        dest: "/tmp/slurm-{{ slurm_version }}.tar.bz2"
        mode: '0644'

    - name: Extract Slurm source
      ansible.builtin.unarchive:
        src: "/tmp/slurm-{{ slurm_version }}.tar.bz2"
        dest: "/tmp/"
        remote_src: yes

    - name: Configure Slurm
      command:
        cmd: ./configure
        chdir: "{{ slurm_build_dir }}"
        creates: "{{ slurm_build_dir }}/Makefile"

    - name: Compile Slurm
      command:
        cmd: make -j$(nproc)
        chdir: "{{ slurm_build_dir }}"
        creates: "{{ slurm_build_dir }}/src/slurmd/slurmd"

    - name: Install Slurm
      command:
        cmd: make install
        chdir: "{{ slurm_build_dir }}"

    - name: Ensure slurm user exists
      ansible.builtin.user:
        name: slurm
        system: yes
        create_home: no
        home: /var/lib/slurm
        shell: /bin/false
        
    - name: Ensure Slurm directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: slurm
        group: slurm
        mode: '0755'
      loop:
        - /var/spool/slurm
        - /var/spool/slurmd
        - /var/log/slurm
        - /usr/local/etc

    - name: Copy slurmd.service to systemd directory
      copy:
        src: "{{ slurm_build_dir }}/etc/slurmd.service"
        dest: "/etc/systemd/system/slurmd.service"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Copy slurm.conf
      copy:
        src: /home/daisy/ansible-playbooks/slurm.conf
        dest: /usr/local/etc/slurm.conf
        owner: slurm
        group: slurm
        mode: '0644'

    - name: Copy cgroup.conf
      copy:
        src: /home/daisy/ansible-playbooks/cgroup.conf
        dest: /usr/local/etc/cgroup.conf
        owner: slurm
        group: slurm
        mode: '0644'

    - name: Start and enable slurmd service
      systemd:
        name: slurmd
        state: started
        enabled: yes
