- name: Setup Daisytuner CLI
  hosts: raspi4
  become: true
  vars:
    snap_file: daisytuner-cli_0.0.5_arm64.snap
    src_snap_path: "/home/daisy/ansible-playbooks/{{ snap_file }}"
    dest_snap_path: "/home/daisy/{{ snap_file }}"
    credentials_src: "/home/daisy/.credentials/"
    credentials_dest: "/var/snap/daisytuner-cli/common/.credentials/"
  tasks:
    - name: Copy snap file to remote
      copy:
        src: "{{ src_snap_path }}"
        dest: "{{ dest_snap_path }}"
        owner: daisy
        mode: '0644'

    - name: Install snap package
      command: "snap install {{ dest_snap_path }} --dangerous --classic"

    - name: Remove snap file after installation
      file:
        path: "{{ dest_snap_path }}"
        state: absent

    - name: Copy credentials to remote
      copy:
        src: "{{ credentials_src }}"
        dest: "{{ credentials_dest }}"
        owner: root
        group: root
        mode: '0600'
