- name: Install Coral Runtime on Ubuntu
  hosts: raspi5
  become: true
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - curl
          - gnupg
          - udev
        state: present

    - name: Add Coral APT key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Coral repository
      apt_repository:
        repo: "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main"
        state: present
        filename: "coral-edgetpu"

    - name: Update APT package cache after adding Coral repo
      apt:
        update_cache: yes

    - name: Install Edge TPU runtime
      apt:
        name: libedgetpu1-std
        state: present
