- name: Update and upgrade the system
  hosts: all
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        yes: yes

    - name: Reboot the system
      reboot:

- name: Install NVIDIA JetPack
  hosts: all
  become: yes
  tasks:
    - name: Install nvidia-jetpack
      apt:
        name: nvidia-jetpack
        state: present
        update_cache: yes

    - name: Add CUDA to PATH
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH=/usr/local/cuda/bin:$PATH'
        create: yes

    - name: Add CUDA to LD_LIBRARY_PATH
      lineinfile:
        path: ~/.bashrc
        line: 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH'
        create: yes
