- name: Install bubblewrap on Linux
  hosts: all
  become: true
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Install bubblewrap on Debian-based systems
      ansible.builtin.apt:
        name: bubblewrap
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install bc on Debian-based systems
      ansible.builtin.apt:
        name: bc
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"



