all:
  hosts: {}
  children:
    
    # Partition: bellis4
    raspi4:
      hosts:
        raspi4-0001:
          ansible_host: 192.168.42.87
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi4-0002:
          ansible_host: 192.168.42.91
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi4-0003:
          ansible_host: 192.168.42.88
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi4-0004:
          ansible_host: 192.168.42.101
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi4-0005:
          ansible_host: 192.168.42.98
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        #raspi4-0006:
        #  ansible_host: 192.168.42.95
        #  ansible_user: daisy
        #  ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"
    
    # Partition: bellis4-ci
    raspi4-ci:
      hosts:
        raspi4-0007:
          ansible_host: 192.168.42.100
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"

    # Partition: bellis5
    raspi5:
      hosts:
        raspi5-0001:
          ansible_host: 192.168.42.89
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0002:
          ansible_host: 192.168.42.90
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0003:
          ansible_host: 192.168.42.96
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0004:
          ansible_host: 192.168.42.85
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0005:
          ansible_host: 192.168.42.94
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0006:
          ansible_host: 192.168.42.95
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0007:
          ansible_host: 192.168.42.102
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0008:
          ansible_host: 192.168.42.97
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0009:
          ansible_host: 192.168.42.93
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0010:
          ansible_host: 192.168.42.92
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0011:
          ansible_host: 192.168.42.99
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"

    # Partition: bellis5-ci
    raspi5-ci:
      hosts:
        raspi5-0012:
          ansible_host: 192.168.42.86
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"

    # Partition: tansy
    jetson:
      hosts:
        jetson-0001:
          ansible_host: 192.168.42.103
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        jetson-0002:
          ansible_host: 192.168.42.104
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        jetson-0003:
          ansible_host: 192.168.42.105
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"

    # Partition: tansy-ci
    jetson-ci:
      hosts:
        jetson-0004:
          ansible_host: 192.168.42.106
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"

    # Partition: zinnia-ci
    zinnia-ci:
      hosts:
        zinnia-0004:
          ansible_host: 192.168.42.118
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"

    # Partition: zinnia
    zinnia:
      hosts:
        zinnia-0003:
          ansible_host: 192.168.42.79
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"

    # Partition: chamomile-ci
    chamomile-ci:
      hosts:
        chamomile-0004:
          ansible_host: 192.168.42.108
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"

    # Partition: chamomile
    chamomile:
      hosts:
        chamomile-0003:
          ansible_host: 192.168.42.78
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"
    # Partition: chamomile

    dahlia:
      hosts:
        dahlia-001:
          ansible_host: 192.168.42.77
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"

    all_nodes:
      children:
        raspi4:
        raspi4-ci:
        raspi5:
        raspi5-ci:
        jetson:
        jetson-ci:
        zinnia-ci:
        chamomile-ci:
        zinnia:
        chamomile:
