all:
  hosts: {}
  children:
    
    # Partition: bellis4
    raspi4:
      hosts:
        raspi4-0001:
          ansible_host: raspi4-0001.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi4-0002:
          ansible_host: raspi4-0002.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi4-0003:
          ansible_host: raspi4-0003.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi4-0004:
          ansible_host: raspi4-0004.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi4-0005:
          ansible_host: raspi4-0005.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        runner_dl_file: runner-dl-v{{ dl_version }}-arm64.tgz
        go_arch: "arm64"
        daisytuner_arch: "arm64"
    
    # Partition: bellis4-ci
    raspi4-ci:
      hosts:
        raspi4-0007:
          ansible_host: raspi4-0007.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-arm64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"
        daisytuner_arch: "arm64"

    # Partition: bellis5
    raspi5:
      hosts:
        raspi5-0001:
          ansible_host: raspi5-0001.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0002:
          ansible_host: raspi5-0002.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0003:
          ansible_host: raspi5-0003.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0004:
          ansible_host: raspi5-0004.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0005:
          ansible_host: raspi5-0005.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0006:
          ansible_host: raspi5-0006.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0007:
          ansible_host: raspi5-0007.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0008:
          ansible_host: raspi5-0008.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0009:
          ansible_host: raspi5-0009.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0010:
          ansible_host: raspi5-0010.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        raspi5-0011:
          ansible_host: raspi5-0011.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-arm64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"
        daisytuner_arch: "arm64"

    # Partition: bellis5-ci
    raspi5-ci:
      hosts:
        raspi5-0012:
          ansible_host: raspi5-0012.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-arm64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"
        daisytuner_arch: "arm64"

    # Partition: tansy
    jetson:
      hosts:
        jetson-0001:
          ansible_host: jetson-0001.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        jetson-0002:
          ansible_host: jetson-0002.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        jetson-0003:
          ansible_host: jetson-0003.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-arm64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"
        daisytuner_arch: "jetson"

    # Partition: tansy-ci
    jetson-ci:
      hosts:
        jetson-0004:
          ansible_host: jetson-0004.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-arm64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"
        daisytuner_arch: "jetson"

    # Partition: zinnia-ci
    zinnia-ci:
      hosts:
        zinnia-0004:
          ansible_host: 192.168.2.34
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-x64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"
        daisytuner_arch: "x64"
        cuda_host_arch: "x86_64"

    # Partition: zinnia
    zinnia:
      hosts:
        zinnia-0001:
          ansible_host: zinnia-0001.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        zinnia-0002:
          ansible_host: zinnia-0002.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        zinnia-0003:
          ansible_host: zinnia-0003.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-x64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"
        daisytuner_arch: "x64"
        cuda_host_arch: "x86_64"

    # Partition: chamomile-ci
    chamomile-ci:
      hosts:
        chamomile-0004:
          ansible_host: chamomile-0004.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-x64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"
        daisytuner_arch: "x64"
        cuda_host_arch: "x86_64"

    # Partition: chamomile
    chamomile:
      hosts:
        chamomile-0001:
          ansible_host: chamomile-0001.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        chamomile-0002: 
          ansible_host: chamomile-0002.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        chamomile-0003:
          ansible_host: chamomile-0003.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-x64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"
        daisytuner_arch: "x64"
        cuda_host_arch: "x86_64"

    dahlia:
      hosts:
        dahlia-0001:
          ansible_host: dahlia-0001.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        dahlia-0005:
          ansible_host: dahlia-0005.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        dahlia-0002: # tenstorrent blackhole
          ansible_host: dahlia-0002.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        dahlia-0003:
          ansible_host: dahlia-0003.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        dahlia-0004:
          ansible_host: dahlia-0004.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        dahlia-0006: # amd GPU
          ansible_host: dahlia-0006.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        dahlia-0007: # amd GPU
          ansible_host: dahlia-0007.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-x64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"
        daisytuner_arch: "x64"
        cuda_host_arch: "x86_64"

    beast:
      hosts:
        beast-0001:
          ansible_host: beast-0001.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        beast-0002:
          ansible_host: beast-0002.lan
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-x64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "amd64"
        daisytuner_arch: "x64"
        cuda_host_arch: "x86_64"

    # Partition: aster 
    aster:
      hosts:
        aster-0001:
          ansible_host: aster-0001.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        aster-0002:
          ansible_host: aster-0002.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
        aster-0003:
          ansible_host: aster-0003.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-arm64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_arm64.snap
        go_arch: "arm64"
        daisytuner_arch: "arm64"
        cuda_host_arch: "sbsa"

    # Partition: aster-ci
    aster-ci:
      hosts:
        aster-0004:
          ansible_host: aster-0004.colo
          ansible_user: daisy
          ansible_python_interpreter: /usr/bin/python3
      vars:
        runner_dl_file: runner-dl-v{{ dl_version }}-x64.tgz
        snap_file: daisytuner-cli_{{ snap_version }}_amd64.snap
        go_arch: "arm64"
        daisytuner_arch: "arm64"
        cuda_host_arch: "sbsa"

    all_nodes:
      children:
        raspi4:
        raspi4-ci:
        raspi5:
        raspi5-ci:
        jetson:
        jetson-ci:
        zinnia-ci:
        chamomile-ci:
        zinnia:
        chamomile:
        aster:
        aster-ci:
