---
- name: Explicitly run APT auto upgrade
  hosts: raspi4,raspi5,jetson
  become: true

  tasks:
    - name: Run apt-get update
      apt:
        update_cache: yes

    - name: Upgrade all packages (normal upgrade)
      apt:
        upgrade: yes

    - name: Upgrade all packages to latest version (dist-upgrade)
      apt:
        upgrade: dist

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes
