---
- name: Explicitly run APT auto upgrade
  hosts: all
  become: true

  tasks:
    - name: Run apt-get update
      apt:
        update_cache: yes

    - name: Upgrade all packages to latest version
      apt:
        upgrade: dist
        update_cache: yes
