- name: Setup Daisytuner CLI
  hosts: chamomile,zinnia,tansy,bellis4,bellis5
  become: true
  vars:
    snap_version: "0.1.0"
  tasks:
    - name: Define snap_file with templated version
      set_fact:
        snap_file: "{{ snap_file | regex_replace('\\{\\{ snap_version \\}\\}', snap_version) }}"

    - name: Set path variables based on snap_file
      set_fact:
        src_snap_path: "/home/daisy/ansible-playbooks/{{ snap_file }}"
        dest_snap_path: "/home/daisy/{{ snap_file }}"

    - name: Copy snap file to remote
      copy:
        src: "{{ src_snap_path }}"
        dest: "{{ dest_snap_path }}"
        owner: daisy
        mode: '0644'

    - name: Install snap package
      command: "snap install {{ dest_snap_path }} --dangerous --classic"

    - name: Remove snap file after installation
      file:
        path: "{{ dest_snap_path }}"
        state: absent

    - name: Restart snap
      command: "snap restart daisytuner-cli.daisytuner-runner"
