- name: Setup Daisytuner CLI
  hosts: jetson,raspi4,raspi5,chamomile,zinnia
  become: true
  vars:
    snap_version: "0.1.0"
  tasks:
    - name: Re-template snap_file using snap_version
      set_fact:
        snap_file: "{{ snap_file_templated }}"
      vars:
        snap_file_templated: "{{ snap_file }}"

    - name: Set path variables based on snap_file
      set_fact:
        src_snap_path: "/home/daisy/ansible-playbooks/{{ snap_file }}"
        dest_snap_path: "/home/daisy/{{ snap_file }}"

    - name: Copy snap file to remote
      copy:
        src: "{{ src_snap_path }}"
        dest: "{{ dest_snap_path }}"
        owner: daisy
        mode: '0644'

    - name: Remove old snap
      command: "snap remove daisytuner-cli"

    - name: Install snap package
      command: "snap install {{ dest_snap_path }} --dangerous --classic"

    - name: Remove snap file after installation
      file:
        path: "{{ dest_snap_path }}"
        state: absent

    - name: Restart snap
      command: "snap start daisytuner-cli.daisytuner-runner"
