---
- name: Disable password-based SSH login on Ubuntu
  hosts: all
  become: true

  vars:
    ssh_config_file: /etc/ssh/sshd_config
    ssh_config_backup: "/etc/ssh/sshd_config.bak.{{ ansible_date_time.iso8601_basic_short }}"
    ssh_config_dir: /etc/ssh/sshd_config.d

  tasks:
    - name: Back up sshd_config
      copy:
        src: "{{ ssh_config_file }}"
        dest: "{{ ssh_config_backup }}"
        remote_src: yes

    - name: Disable PasswordAuthentication in sshd_config
      lineinfile:
        path: "{{ ssh_config_file }}"
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Disable ChallengeResponseAuthentication in sshd_config
      lineinfile:
        path: "{{ ssh_config_file }}"
        regexp: '^#?ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication no'
        state: present

    - name: Disable UsePAM in sshd_config
      lineinfile:
        path: "{{ ssh_config_file }}"
        regexp: '^#?UsePAM'
        line: 'UsePAM no'
        state: present

    - name: Search for and patch PasswordAuthentication yes in sshd_config.d
      find:
        paths: "{{ ssh_config_dir }}"
        patterns: "*.conf"
        contains: "^\\s*PasswordAuthentication\\s+yes"
      register: override_files

    - name: Replace PasswordAuthentication yes with no in override files
      replace:
        path: "{{ item.path }}"
        regexp: '^\s*PasswordAuthentication\s+yes'
        replace: 'PasswordAuthentication no'
      loop: "{{ override_files.files }}"
      when: override_files.matched > 0

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted

    - name: Print final status
      debug:
        msg: |
           Password-based SSH login is now fully disabled.
           All overrides in /etc/ssh/sshd_config.d were checked and corrected.
           Be sure your SSH key access is working before logging out!

