---
- name: Install Tenstorrent kernel module
  hosts: dahlia
  
  tasks:
    - name: Create tenstorrent wheels dir
      become: true
      file:
        path: /opt/tenstorrent/wheels
        owner: daisy
        group: daisy
        mode: '0755'
        state: directory
    - name: Copy tenstorrent wheels
      ansible.posix.synchronize:
        src: "/home/daisy/ttnn-support/wheels/"
        dest: "/opt/tenstorrent/wheels"
        delete: true
