- name: Setup Daisytuner CLI
  hosts: jetson-ci
  become: true
  tasks:
    - name: Prune docker
      command: "docker system prune -a -f"

    - name: Pull docker
      command: "docker pull daisytuner/jetson:latest"
