- name: Setup Daisytuner CLI
  hosts: raspi4,raspi5
  become: true
  tasks:
    - name: Prune docker
      command: "docker system prune -a -f"

    - name: Pull docker
      command: "docker pull daisytuner/arm64:latest"

