fw_version: "18.12.0"
tt_kmd_path: "/tmp/tt-kmd"
tt_kmd_version: "ttkmd-2.4.1"
tt_smi_version: "v3.0.30"
tt_venv_path: "/opt/tt"
deb_url: "https://github.com/tenstorrent/tt-system-tools/releases/download/v1.4.0/tenstorrent-tools_1.4.0_all.deb"
deb_file: "/tmp/tenstorrent.deb"