
- name: Install Debian Prerequisites
  apt:
    name:
      - git
      - build-essential
      - cmake
      - ninja-build
      - pkg-config
      - cargo
      - g++-12
      - pandoc
      - xz-utils
      - python3-dev
      - python3-pip
      - python3-venv
      - libhwloc-dev
      - libnuma-dev
      - libatomic1
      - libstdc++6
      - libboost-dev
      - libtbb-dev
      - libcapstone-dev
      - libc++-17-dev
      - libc++abi-17-dev
      - wget
    state: present

    #incomplete, we are just using their script