
- name: Ensure standard packages are installed
  package:
    name:
      - wget
      - curl
      - gnupg2
      - software-properties-common
      - build-essential
      - cmake
      - ninja-build
      - git
      - git-lfs
      - pkg-config
      - unzip
      - file
    state: present
  become: yes
